/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "laccljymjmomrvtyceih"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhY2Nsanltam1vbXJ2dHljZWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyNjIxNjIsImV4cCI6MjEwMjgzODE2Mn0.RCBs0yDYq1Wh_YIP_KzMywKOuW3H-VFzodOSxRN0s2Y"
